// ═══════════════════════════════════════════════════
//  tools/generateMoves.js
//  Run AFTER generatePokemon.js to expand moves.js
//  with every move referenced by your Pokémon data.
//
//  RUN:
//    node tools/generateMoves.js
//
//  OUTPUT:
//    src/data/moves.js   (overwrites existing file)
// ═══════════════════════════════════════════════════

const fs   = require('fs');
const path = require('path');

const REQUEST_DELAY = 100;
function delay(ms) { return new Promise(r => setTimeout(r, ms)); }

async function fetchJSON(url, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
      return await res.json();
    } catch (err) {
      if (i === retries - 1) throw err;
      await delay(400);
    }
  }
}

function toCamelCase(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// ─── Type chart (Gen 6, static — doesn't change) ──
const TYPE_CHART = {
  normal:   { rock:0.5, ghost:0, steel:0.5 },
  fire:     { fire:0.5, water:0.5, grass:2, ice:2, bug:2, rock:0.5, dragon:0.5, steel:2 },
  water:    { fire:2, water:0.5, grass:0.5, ground:2, rock:2, dragon:0.5 },
  electric: { water:2, electric:0.5, grass:0.5, ground:0, flying:2, dragon:0.5 },
  grass:    { fire:0.5, water:2, grass:0.5, poison:0.5, ground:2, flying:0.5, bug:0.5, rock:2, dragon:0.5, steel:0.5 },
  ice:      { fire:0.5, water:0.5, grass:2, ice:0.5, ground:2, flying:2, dragon:2, steel:0.5 },
  fighting: { normal:2, ice:2, poison:0.5, flying:0.5, psychic:0.5, bug:0.5, rock:2, ghost:0, dark:2, steel:2, fairy:0.5 },
  poison:   { grass:2, poison:0.5, ground:0.5, rock:0.5, ghost:0.5, steel:0, fairy:2 },
  ground:   { fire:2, electric:2, grass:0.5, poison:2, flying:0, bug:0.5, rock:2, steel:2 },
  flying:   { electric:0.5, grass:2, fighting:2, bug:2, rock:0.5, steel:0.5 },
  psychic:  { fighting:2, poison:2, psychic:0.5, dark:0, steel:0.5 },
  bug:      { fire:0.5, grass:2, fighting:0.5, flying:0.5, psychic:2, ghost:0.5, dark:2, steel:0.5, fairy:0.5 },
  rock:     { fire:2, ice:2, fighting:0.5, ground:0.5, flying:2, bug:2, steel:0.5 },
  ghost:    { normal:0, psychic:2, ghost:2, dark:0.5 },
  dragon:   { dragon:2, steel:0.5, fairy:0 },
  dark:     { fighting:0.5, psychic:2, ghost:2, dark:0.5, fairy:0.5 },
  steel:    { fire:0.5, water:0.5, electric:0.5, ice:2, rock:2, steel:0.5, fairy:2 },
  fairy:    { fire:0.5, fighting:2, poison:0.5, dragon:2, dark:2, steel:0.5 },
};

// ─── Read the generated pokemon.js to get move keys ─
function extractMoveKeys() {
  const pkmnFile = fs.readFileSync(
    path.join(__dirname, '..', 'src', 'data', 'pokemon.js'), 'utf8'
  );
  const moveSet = new Set();
  const moveRegex = /moves:\s*\[(.*?)\]/gs;
  let match;
  while ((match = moveRegex.exec(pkmnFile)) !== null) {
    const keys = match[1].match(/["']([^"']+)["']/g) || [];
    keys.forEach(k => moveSet.add(k.replace(/['"]/g, '')));
  }
  return [...moveSet];
}

// ─── Fetch a single move from PokeAPI ─────────────
async function fetchMove(moveName) {
  const apiName = moveName.replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, '');
  const data = await fetchJSON(`https://pokeapi.co/api/v2/move/${apiName}`);

  return {
    key:      toCamelCase(data.name),
    name:     data.name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
    type:     data.type.name,
    category: data.damage_class?.name || 'status',
    power:    data.power    || 0,
    accuracy: data.accuracy || 100,
    pp:       data.pp       || 10,
  };
}

// ─── Main ─────────────────────────────────────────
async function main() {
  console.log('🎮 PokéArena — Generating moves.js from PokeAPI\n');

  const moveKeys = extractMoveKeys();
  console.log(`Found ${moveKeys.length} unique move keys in pokemon.js\n`);

  const moves = [];
  const failed = [];

  for (let i = 0; i < moveKeys.length; i++) {
    const key = moveKeys[i];
    process.stdout.write(`  [${i+1}/${moveKeys.length}] ${key}... `);
    try {
      const move = await fetchMove(key);
      moves.push(move);
      console.log(`✓ ${move.name} (${move.type}, ${move.category}, pwr:${move.power})`);
    } catch (err) {
      console.warn(`✗ not found in API`);
      failed.push(key);
    }
    await delay(REQUEST_DELAY);
  }

  // ─── Generate moves.js ────────────────────────
  const lines = [
    `// AUTO-GENERATED by tools/generateMoves.js`,
    `// Generated: ${new Date().toISOString()}`,
    `// ${moves.length} moves fetched, ${failed.length} failed.`,
    ``,
    `const MOVES_DATA = {`,
  ];

  for (const m of moves) {
    lines.push(`  ${m.key}: {`);
    lines.push(`    name:'${m.name}', type:'${m.type}', category:'${m.category}',`);
    lines.push(`    power:${m.power}, accuracy:${m.accuracy === null ? 100 : m.accuracy}, pp:${m.pp},`);
    lines.push(`  },`);
  }

  if (failed.length > 0) {
    lines.push(``);
    lines.push(`  // ─── Manual fallbacks for API misses ───`);
    for (const key of failed) {
      lines.push(`  ${key}: { name:'${key}', type:'normal', category:'physical', power:40, accuracy:100, pp:35 },`);
    }
  }

  lines.push(`};`);
  lines.push(``);
  lines.push(`// ─── Type chart ────────────────────────────`);
  lines.push(`const TYPE_CHART = ${JSON.stringify(TYPE_CHART, null, 2)};`);
  lines.push(``);
  lines.push(`function getTypeEffectiveness(attackType, defenderTypes) {`);
  lines.push(`  let multiplier = 1;`);
  lines.push(`  for (const defType of defenderTypes) {`);
  lines.push(`    const row = TYPE_CHART[attackType];`);
  lines.push(`    if (row && row[defType] !== undefined) multiplier *= row[defType];`);
  lines.push(`  }`);
  lines.push(`  return multiplier;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`function getEffectivenessText(mult) {`);
  lines.push(`  if (mult === 0)  return "It doesn't affect the foe...";`);
  lines.push(`  if (mult < 1)    return "It's not very effective...";`);
  lines.push(`  if (mult === 1)  return "";`);
  lines.push(`  if (mult >= 2)   return "It's super effective!";`);
  lines.push(`}`);

  const outPath = path.join(__dirname, '..', 'src', 'data', 'moves.js');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');

  console.log(`\n✅ Done! Written to ${outPath}`);
  if (failed.length > 0) {
    console.log(`\n⚠️  ${failed.length} moves used fallback (normal/physical/40 power):`);
    console.log(`   ${failed.join(', ')}`);
    console.log(`   These likely need manual correction in moves.js`);
  }
}

main().catch(console.error);
