// ═══════════════════════════════════════════════════
//  tools/generateLearnsets.js
//  Fetches level-up learnsets for all Pokémon
//  in your pokemon.js and generates learnsets.js.
//
//  RUN (after generatePokemon.js):
//    node tools/generateLearnsets.js
//
//  OUTPUT:
//    src/data/learnsets.js
// ═══════════════════════════════════════════════════

const fs   = require('fs');
const path = require('path');

const REQUEST_DELAY = 120;
function delay(ms) { return new Promise(r => setTimeout(r, ms)); }

async function fetchJSON(url, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (e) {
      if (i === retries - 1) throw e;
      await delay(400);
    }
  }
}

function toCamelCase(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// Extract all Pokémon keys from pokemon.js
function extractPokemonKeys() {
  const file = fs.readFileSync(
    path.join(__dirname, '..', 'src', 'data', 'pokemon.js'), 'utf8'
  );
  const keys = [];
  const re = /^\s{2}(\w+): \{/gm;
  let m;
  while ((m = re.exec(file)) !== null) {
    if (!['getSpriteUrl','getBackSpriteUrl','createPokemonInstance',
          'getUnlockedPokemon','unlockPokemon'].includes(m[1])) {
      keys.push(m[1]);
    }
  }
  return keys;
}

// Fetch level-up learnset for one Pokémon
// Returns array of [level, moveKey] pairs, deduplicated and sorted
async function fetchLearnset(pokemonKey) {
  // Convert camelCase back to kebab-case for PokeAPI
  const apiName = pokemonKey.replace(/([A-Z])/g, '-$1').toLowerCase();
  const data = await fetchJSON(`https://pokeapi.co/api/v2/pokemon/${apiName}`);

  const learnset = [];
  const seen = new Set();

  for (const moveEntry of data.moves) {
    // Find level-up entries (prefer "red-blue" or "scarlet-violet" version group)
    const levelUpEntry = moveEntry.version_group_details
      .filter(d => d.move_learn_method.name === 'level-up')
      .sort((a, b) => {
        // Prefer more recent game (higher version group ID in URL)
        const aId = parseInt(a.version_group.url.split('/').slice(-2)[0]);
        const bId = parseInt(b.version_group.url.split('/').slice(-2)[0]);
        return bId - aId;
      })[0];

    if (!levelUpEntry) continue;

    const level   = levelUpEntry.level_learned_at;
    const moveKey = toCamelCase(moveEntry.move.name);
    const uniqKey = `${level}:${moveKey}`;

    if (!seen.has(uniqKey) && level > 0) {
      seen.add(uniqKey);
      learnset.push([level, moveKey]);
    }
  }

  return learnset.sort((a, b) => a[0] - b[0]);
}

async function main() {
  console.log('🎮 PokéArena — Generating learnsets.js\n');

  const keys = extractPokemonKeys();
  console.log(`Found ${keys.length} Pokémon in pokemon.js\n`);

  const results = {};

  for (let i = 0; i < keys.length; i++) {
    const key = keys[i];
    process.stdout.write(`  [${i+1}/${keys.length}] ${key}... `);
    try {
      const learnset = await fetchLearnset(key);
      results[key] = learnset;
      console.log(`✓ ${learnset.length} moves`);
    } catch (err) {
      console.warn(`✗ failed: ${err.message}`);
      results[key] = [];
    }
    await delay(REQUEST_DELAY);
  }

  // Generate learnsets.js
  const lines = [
    `// AUTO-GENERATED by tools/generateLearnsets.js`,
    `// Generated: ${new Date().toISOString()}`,
    ``,
    `const LEARNSETS = {`,
  ];

  for (const [key, learnset] of Object.entries(results)) {
    if (learnset.length === 0) continue;
    lines.push(`  ${key}: [`);
    for (const [lv, mv] of learnset) {
      lines.push(`    [${lv}, '${mv}'],`);
    }
    lines.push(`  ],`);
  }

  lines.push(`};`);
  lines.push(``);
  lines.push(`function getNewMovesAtLevel(key, level, knownMoveIds) {`);
  lines.push(`  const learnset = LEARNSETS[key] || [];`);
  lines.push(`  return learnset`);
  lines.push(`    .filter(([lv, mk]) => lv === level && !knownMoveIds.includes(mk))`);
  lines.push(`    .map(([lv, mk]) => ({ level: lv, moveKey: mk }));`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`function getLearnsetUpToLevel(key, upToLevel) {`);
  lines.push(`  const learnset = LEARNSETS[key] || [];`);
  lines.push(`  return learnset`);
  lines.push(`    .filter(([lv]) => lv <= upToLevel)`);
  lines.push(`    .map(([lv, mk]) => ({ level: lv, moveKey: mk, move: MOVES_DATA[mk] }))`);
  lines.push(`    .filter(e => e.move);`);
  lines.push(`}`);

  const outPath = path.join(__dirname, '..', 'src', 'data', 'learnsets.js');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');

  console.log(`\n✅ Done! Written to ${outPath}`);
  console.log(`   ${Object.keys(results).length} Pokémon, ${Object.values(results).flat().length} total move entries`);
}

main().catch(console.error);
