// ═══════════════════════════════════════════════════
//  tools/generateEvolutions.js
//  Fetches evolution chains for all Pokémon in
//  pokemon.js and adds them to evolution.js.
//
//  RUN (after generatePokemon.js):
//    node tools/generateEvolutions.js
//
//  OUTPUT:
//    src/pokemon/evolution.js  (overwrites file)
// ═══════════════════════════════════════════════════

const fs   = require('fs');
const path = require('path');

const REQUEST_DELAY = 120;
function delay(ms) { return new Promise(r => setTimeout(r, ms)); }

async function fetchJSON(url, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (e) {
      if (i === retries - 1) throw e;
      await delay(400);
    }
  }
}

function toCamelCase(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function extractPokemonKeys() {
  const file = fs.readFileSync(
    path.join(__dirname, '..', 'src', 'data', 'pokemon.js'), 'utf8'
  );
  const keys = [];
  const re = /^\s{2}(\w+): \{/gm;
  let m;
  while ((m = re.exec(file)) !== null) {
    if (!['getSpriteUrl','getBackSpriteUrl','createPokemonInstance',
          'getUnlockedPokemon','unlockPokemon'].includes(m[1])) {
      keys.push(m[1]);
    }
  }
  return new Set(keys);
}

// Walk an evolution chain node recursively, extract level-based evolutions
function walkChain(node, table, validKeys) {
  for (const next of node.evolves_to) {
    const fromKey = toCamelCase(node.species.name);
    const toKey   = toCamelCase(next.species.name);

    if (!validKeys.has(fromKey) || !validKeys.has(toKey)) {
      walkChain(next, table, validKeys);
      continue;
    }

    // Find level-up trigger (if any)
    const levelDetail = next.evolution_details.find(
      d => d.trigger?.name === 'level-up' && d.min_level
    );

    if (levelDetail) {
      table[fromKey] = { into: toKey, level: levelDetail.min_level };
    }
    // Item / friendship evolutions: simplified to level 30
    else if (next.evolution_details.length > 0) {
      table[fromKey] = { into: toKey, level: 30 };
    }

    walkChain(next, table, validKeys);
  }
}

async function main() {
  console.log('🎮 PokéArena — Generating evolution.js\n');

  const validKeys = extractPokemonKeys();
  const table = {};
  const processed = new Set();

  // Fetch evolution chains via species endpoint
  for (const key of validKeys) {
    const apiName = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    process.stdout.write(`  ${key}... `);
    try {
      const species = await fetchJSON(`https://pokeapi.co/api/v2/pokemon-species/${apiName}`);
      const chainId = species.evolution_chain.url;

      if (processed.has(chainId)) { console.log('(cached)'); continue; }
      processed.add(chainId);

      const chainData = await fetchJSON(chainId);
      walkChain(chainData.chain, table, validKeys);
      console.log('✓');
    } catch (e) {
      console.warn(`✗ ${e.message}`);
    }
    await delay(REQUEST_DELAY);
  }

  // Generate evolution.js
  const lines = [
    `// AUTO-GENERATED by tools/generateEvolutions.js`,
    `// Generated: ${new Date().toISOString()}`,
    ``,
    `const EvolutionSystem = (() => {`,
    ``,
    `  const EVOLUTION_TABLE = {`,
  ];

  for (const [from, evo] of Object.entries(table)) {
    lines.push(`    ${from}: { into: '${evo.into}', level: ${evo.level} },`);
  }

  lines.push(`  };`);
  lines.push(``);
  lines.push(`  function checkEvolution(key, level) {`);
  lines.push(`    const evo = EVOLUTION_TABLE[key];`);
  lines.push(`    if (!evo) return null;`);
  lines.push(`    return level >= evo.level ? evo : null;`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  function evolve(fromKey, toKey, slotIndex) {`);
  lines.push(`    if (!POKEMON_DATA[toKey]) return false;`);
  lines.push(`    const team = SaveSystem.getTeam();`);
  lines.push(`    if (team[slotIndex] !== fromKey) return false;`);
  lines.push(`    team[slotIndex] = toKey;`);
  lines.push(`    SaveSystem.setTeam(team);`);
  lines.push(`    SaveSystem.unlockPokemon(toKey);`);
  lines.push(`    return true;`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  function checkTeamEvolutions(battleTeam) {`);
  lines.push(`    const events = [];`);
  lines.push(`    battleTeam.forEach((pkmn, i) => {`);
  lines.push(`      const evo = checkEvolution(pkmn.key, pkmn.level);`);
  lines.push(`      if (evo) {`);
  lines.push(`        const success = evolve(pkmn.key, evo.into, i);`);
  lines.push(`        if (success) events.push({`);
  lines.push(`          fromName: POKEMON_DATA[pkmn.key]?.name,`);
  lines.push(`          toName:   POKEMON_DATA[evo.into]?.name,`);
  lines.push(`          fromKey:  pkmn.key, toKey: evo.into, slotIndex: i`);
  lines.push(`        });`);
  lines.push(`      }`);
  lines.push(`    });`);
  lines.push(`    return events;`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  function getChainString(startKey) {`);
  lines.push(`    const parts = [POKEMON_DATA[startKey]?.name || startKey];`);
  lines.push(`    let current = startKey;`);
  lines.push(`    for (let i = 0; i < 5; i++) {`);
  lines.push(`      const evo = EVOLUTION_TABLE[current];`);
  lines.push(`      if (!evo) break;`);
  lines.push(`      parts.push(\`→ \${POKEMON_DATA[evo.into]?.name || evo.into} (Lv.\${evo.level})\`);`);
  lines.push(`      current = evo.into;`);
  lines.push(`    }`);
  lines.push(`    return parts.join(' ');`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  return { checkEvolution, evolve, checkTeamEvolutions, getChainString };`);
  lines.push(`})()`);
  lines.push(`;`);

  const outPath = path.join(__dirname, '..', 'src', 'pokemon', 'evolution.js');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');

  console.log(`\n✅ Done! Written to ${outPath}`);
  console.log(`   ${Object.keys(table).length} evolution entries generated`);
}

main().catch(console.error);
